import type { FamilyRole } from "@/lib/family-auth";

export type ServicesLanguage = "fr" | "en" | "ar";
export type ServicesViewMode = "buyer" | "requester";

export function normalizeServicesLanguage(value: unknown): ServicesLanguage {
  return value === "en" || value === "ar" ? value : "fr";
}

export function servicesViewMode(role: FamilyRole): ServicesViewMode {
  return role === "delivery" ? "buyer" : "requester";
}

export const servicesCopy = {
  fr: {
    workspace: "Mon espace",
    pageName: "Services",
    pageEyebrow: "Missions maison",
    buyerTitle: "Vos missions",
    buyerDescription: "Commencez ou terminez les missions qui vous sont confiées.",
    requesterTitle: "Choisir un service",
    requesterDescription: "Créez une demande familiale ou personnelle, puis suivez son avancement.",
    plan: "Forfait",
    familyPlan: "Forfait familial",
    personalPlan: "Forfait personnel",
    openPlan: "Voir le forfait et les limites",
    unlimited: "Services illimités",
    remaining: "restants",
    used: "utilisés",
    scopeLabel: "Type de service",
    family: "Famille",
    personal: "Personnel",
    familyServices: "Services familiaux",
    personalServices: "Services personnels",
    familyDescription: "Pour les espaces et les besoins partagés par toute la maison.",
    personalDescription: "Pour une demande privée, payée uniquement par vous.",
    buyerCatalogTitle: "Créer une mission",
    buyerCatalogDescription: "Consultez les services disponibles si vous devez ajouter une demande.",
    catalog: "Catalogue",
    yourMissions: "Vos missions",
    nextActions: "Prochaines actions",
    requests: "Suivi des demandes",
    active: "Actives",
    completed: "Terminées",
    cancelled: "Annulées",
    missionSingular: "mission",
    missionPlural: "missions",
    noActiveBuyerTitle: "Aucune mission à faire pour le moment.",
    noActiveBuyerDescription: "Les nouvelles demandes familiales ou personnelles apparaîtront ici.",
    noActiveRequesterTitle: "Aucune demande active.",
    noActiveRequesterDescription: "Choisissez un service ci-dessus pour créer la première demande.",
    noCompletedTitle: "Aucune mission terminée.",
    noCompletedDescription: "Les missions terminées apparaîtront ici.",
    noCancelledTitle: "Aucune mission annulée.",
    noCancelledDescription: "Les missions annulées apparaîtront ici.",
    statusPending: "À faire",
    statusInProgress: "En cours",
    statusCompleted: "Terminée",
    statusCancelled: "Annulée",
    requestedBy: "Demandé par",
    price: "Prix",
    start: "Commencer",
    finish: "Terminer",
    cancelMission: "Annuler la mission",
    taskStarted: "Mission commencée.",
    taskCompleted: "Bravo, mission terminée !",
    taskCancelled: "Mission annulée.",
    everyWeek: "Chaque semaine",
    everyMonth: "Chaque mois",
    viewDetails: "voir les détails",
    from: "Dès",
    loading: "Chargement des services…",
    retry: "Réessayer",
    loadError: "Chargement impossible.",
    dialogDescription: "Détails et commande du service",
    familyService: "Service familial",
    personalService: "Service personnel",
    servicePrice: "Prix du service",
    whatBuyerWillDo: "Ce que l’acheteur va faire",
    whatYouWillDo: "Ce que vous allez faire",
    serviceName: "Nom du service",
    familyNameExample: "Ex. Arroser les plantes",
    personalNameExample: "Ex. Organiser mes fichiers",
    instructionsBuyer: "Instructions pour l’acheteur (facultatif)",
    instructionsBuyerPlaceholder: "Lieu, quantité ou détail important…",
    instructionsSelf: "Instructions de la mission (facultatif)",
    instructionsSelfPlaceholder: "Lieu, quantité ou détail important…",
    completedBy: "Réalisé par",
    assignedToYou: "Assignée à vous",
    proposedPrice: "Prix proposé (2–49 DH)",
    fixedPrice: "Prix fixé",
    desiredDate: "Date souhaitée",
    priority: "Priorité",
    normal: "Normale",
    urgent: "Urgente",
    recurrence: "Répétition",
    once: "Une seule fois",
    plusRequired: "Plus requis",
    requestService: "Demander ce service",
    createMission: "Créer cette mission",
    familyRequested: "Service familial demandé.",
    personalRequested: "Service personnel demandé.",
    missionCreated: "Mission créée.",
    actionError: "Action impossible.",
    serviceLimit: "Limite de services",
  },
  en: {
    workspace: "My workspace",
    pageName: "Services",
    pageEyebrow: "Home missions",
    buyerTitle: "Your missions",
    buyerDescription: "Start or finish the missions assigned to you.",
    requesterTitle: "Choose a service",
    requesterDescription: "Create a family or personal request, then track its progress.",
    plan: "Plan",
    familyPlan: "Family plan",
    personalPlan: "Personal plan",
    openPlan: "View plan and limits",
    unlimited: "Unlimited services",
    remaining: "remaining",
    used: "used",
    scopeLabel: "Service type",
    family: "Family",
    personal: "Personal",
    familyServices: "Family services",
    personalServices: "Personal services",
    familyDescription: "For spaces and needs shared by the whole household.",
    personalDescription: "For a private request paid only by you.",
    buyerCatalogTitle: "Create a mission",
    buyerCatalogDescription: "Browse available services if you need to add a request.",
    catalog: "Catalogue",
    yourMissions: "Your missions",
    nextActions: "Next actions",
    requests: "Request tracking",
    active: "Active",
    completed: "Completed",
    cancelled: "Cancelled",
    missionSingular: "mission",
    missionPlural: "missions",
    noActiveBuyerTitle: "No missions to do right now.",
    noActiveBuyerDescription: "New family or personal requests will appear here.",
    noActiveRequesterTitle: "No active requests.",
    noActiveRequesterDescription: "Choose a service above to create the first request.",
    noCompletedTitle: "No completed missions yet.",
    noCompletedDescription: "Completed missions will appear here.",
    noCancelledTitle: "No cancelled missions.",
    noCancelledDescription: "Cancelled missions will appear here.",
    statusPending: "To do",
    statusInProgress: "In progress",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    requestedBy: "Requested by",
    price: "Price",
    start: "Start",
    finish: "Finish",
    cancelMission: "Cancel mission",
    taskStarted: "Mission started.",
    taskCompleted: "Mission completed. Well done!",
    taskCancelled: "Mission cancelled.",
    everyWeek: "Every week",
    everyMonth: "Every month",
    viewDetails: "view details",
    from: "From",
    loading: "Loading services…",
    retry: "Try again",
    loadError: "Unable to load.",
    dialogDescription: "Service details and request",
    familyService: "Family service",
    personalService: "Personal service",
    servicePrice: "Service price",
    whatBuyerWillDo: "What the buyer will do",
    whatYouWillDo: "What you will do",
    serviceName: "Service name",
    familyNameExample: "E.g. Water the plants",
    personalNameExample: "E.g. Organize my files",
    instructionsBuyer: "Instructions for the buyer (optional)",
    instructionsBuyerPlaceholder: "Place, quantity, or an important detail…",
    instructionsSelf: "Mission instructions (optional)",
    instructionsSelfPlaceholder: "Place, quantity, or an important detail…",
    completedBy: "Completed by",
    assignedToYou: "Assigned to you",
    proposedPrice: "Proposed price (2–49 DH)",
    fixedPrice: "Fixed price",
    desiredDate: "Preferred date",
    priority: "Priority",
    normal: "Normal",
    urgent: "Urgent",
    recurrence: "Repeat",
    once: "Once",
    plusRequired: "Plus required",
    requestService: "Request this service",
    createMission: "Create this mission",
    familyRequested: "Family service requested.",
    personalRequested: "Personal service requested.",
    missionCreated: "Mission created.",
    actionError: "Unable to complete the action.",
    serviceLimit: "Service allowance",
  },
  ar: {
    workspace: "مساحتي",
    pageName: "الخدمات",
    pageEyebrow: "مهام الدار",
    buyerTitle: "مهامك",
    buyerDescription: "ابدأ أو أكمل المهام المسندة إليك.",
    requesterTitle: "اختيار خدمة",
    requesterDescription: "أنشئ طلباً عائلياً أو شخصياً وتابع تقدمه.",
    plan: "الباقة",
    familyPlan: "باقة العائلة",
    personalPlan: "الباقة الشخصية",
    openPlan: "عرض الباقة والحدود",
    unlimited: "خدمات غير محدودة",
    remaining: "متبقية",
    used: "مستعملة",
    scopeLabel: "نوع الخدمة",
    family: "العائلة",
    personal: "شخصي",
    familyServices: "خدمات العائلة",
    personalServices: "خدمات شخصية",
    familyDescription: "للمساحات والاحتياجات المشتركة بين أفراد الدار.",
    personalDescription: "لطلب خاص تؤدي ثمنه وحدك.",
    buyerCatalogTitle: "إنشاء مهمة",
    buyerCatalogDescription: "تصفح الخدمات المتاحة إذا احتجت إلى إضافة طلب.",
    catalog: "دليل الخدمات",
    yourMissions: "مهامك",
    nextActions: "الخطوات التالية",
    requests: "تتبع الطلبات",
    active: "نشطة",
    completed: "مكتملة",
    cancelled: "ملغاة",
    missionSingular: "مهمة",
    missionPlural: "مهام",
    noActiveBuyerTitle: "لا توجد مهام الآن.",
    noActiveBuyerDescription: "ستظهر هنا الطلبات العائلية أو الشخصية الجديدة.",
    noActiveRequesterTitle: "لا توجد طلبات نشطة.",
    noActiveRequesterDescription: "اختر خدمة أعلاه لإنشاء أول طلب.",
    noCompletedTitle: "لا توجد مهام مكتملة بعد.",
    noCompletedDescription: "ستظهر المهام المكتملة هنا.",
    noCancelledTitle: "لا توجد مهام ملغاة.",
    noCancelledDescription: "ستظهر المهام الملغاة هنا.",
    statusPending: "للإنجاز",
    statusInProgress: "قيد الإنجاز",
    statusCompleted: "مكتملة",
    statusCancelled: "ملغاة",
    requestedBy: "طلبها",
    price: "الثمن",
    start: "ابدأ",
    finish: "أنهِ",
    cancelMission: "إلغاء المهمة",
    taskStarted: "بدأت المهمة.",
    taskCompleted: "أحسنت، اكتملت المهمة!",
    taskCancelled: "أُلغيت المهمة.",
    everyWeek: "كل أسبوع",
    everyMonth: "كل شهر",
    viewDetails: "عرض التفاصيل",
    from: "ابتداءً من",
    loading: "جارٍ تحميل الخدمات…",
    retry: "إعادة المحاولة",
    loadError: "تعذر التحميل.",
    dialogDescription: "تفاصيل الخدمة وطلبها",
    familyService: "خدمة عائلية",
    personalService: "خدمة شخصية",
    servicePrice: "ثمن الخدمة",
    whatBuyerWillDo: "ما الذي سيفعله المشتري",
    whatYouWillDo: "ما الذي ستفعله",
    serviceName: "اسم الخدمة",
    familyNameExample: "مثال: سقي النباتات",
    personalNameExample: "مثال: ترتيب ملفاتي",
    instructionsBuyer: "تعليمات للمشتري (اختياري)",
    instructionsBuyerPlaceholder: "المكان أو الكمية أو تفصيل مهم…",
    instructionsSelf: "تعليمات المهمة (اختياري)",
    instructionsSelfPlaceholder: "المكان أو الكمية أو تفصيل مهم…",
    completedBy: "ينفذها",
    assignedToYou: "مسندة إليك",
    proposedPrice: "الثمن المقترح (2–49 درهم)",
    fixedPrice: "ثمن ثابت",
    desiredDate: "التاريخ المطلوب",
    priority: "الأولوية",
    normal: "عادية",
    urgent: "مستعجلة",
    recurrence: "التكرار",
    once: "مرة واحدة",
    plusRequired: "تحتاج باقة Plus",
    requestService: "اطلب هذه الخدمة",
    createMission: "أنشئ هذه المهمة",
    familyRequested: "تم طلب خدمة عائلية.",
    personalRequested: "تم طلب خدمة شخصية.",
    missionCreated: "تم إنشاء المهمة.",
    actionError: "تعذر تنفيذ العملية.",
    serviceLimit: "حد الخدمات",
  },
} as const;
