create table if not exists public.app_meta (
  key text primary key,
  value text not null
);

create table if not exists public.family_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password_hash text not null default '',
  role text not null check (role in ('admin', 'delivery', 'member')),
  initials text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.family_sessions (
  token_hash text primary key,
  user_id bigint not null references public.family_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null default '',
  name_en text not null default '',
  category text not null check (category in ('food', 'cleaning', 'hygiene', 'school', 'household', 'health')),
  unit text not null check (unit in ('L', 'kg', 'pièce')),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  image_position text not null default '0% 0%',
  image_url text,
  barcode text unique,
  package_size text,
  external_source text,
  external_id text,
  purchase_count integer not null default 0 check (purchase_count >= 0),
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (external_source, external_id)
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.family_users(id),
  status text not null default 'pending' check (status in ('pending', 'ready', 'shopping', 'completed', 'cancelled')),
  priority text check (priority in ('urgent', 'normal')),
  created_at timestamptz not null default now(),
  submitted_at timestamptz not null default now(),
  approved_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity_hundredths integer not null check (quantity_hundredths > 0),
  requested_unit_price_cents integer not null check (requested_unit_price_cents >= 0),
  actual_unit_price_cents integer not null check (actual_unit_price_cents >= 0),
  purchase_status text not null default 'requested' check (purchase_status in ('requested', 'bought', 'unbought'))
);

create index if not exists idx_family_sessions_user_id on public.family_sessions(user_id);
create index if not exists idx_family_sessions_expires_at on public.family_sessions(expires_at);
create index if not exists idx_products_name_fr on public.products(name_fr);
create index if not exists idx_products_category_active on public.products(category, active);
create index if not exists idx_carts_member_status on public.carts(member_id, status);
create index if not exists idx_carts_queue on public.carts(status, priority, submitted_at);
create index if not exists idx_carts_completed_at on public.carts(completed_at);
create index if not exists idx_cart_items_cart_id on public.cart_items(cart_id);
create index if not exists idx_cart_items_product_id on public.cart_items(product_id);

alter table public.app_meta enable row level security;
alter table public.family_users enable row level security;
alter table public.family_sessions enable row level security;
alter table public.products enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;

revoke all on table public.app_meta, public.family_users, public.family_sessions,
  public.products, public.carts, public.cart_items from anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.app_meta, public.family_users,
  public.family_sessions, public.products, public.carts, public.cart_items to service_role;
grant usage, select, update on all sequences in schema public to service_role;

insert into public.family_users (id, name, username, role, initials, active)
values
  (1, 'Youssef', 'youssef', 'admin', 'YO', true),
  (2, 'Salma', 'salma', 'delivery', 'SA', true),
  (3, 'Papa', 'papa', 'member', 'PA', true),
  (4, 'Maman', 'maman', 'member', 'MA', true),
  (5, 'Amina', 'amina', 'member', 'AM', true),
  (6, 'Yassine', 'yassine', 'member', 'YA', true),
  (7, 'Sara', 'sara', 'member', 'SR', true),
  (8, 'Adam', 'adam', 'member', 'AD', true)
on conflict (id) do update set
  name = excluded.name,
  username = excluded.username,
  role = excluded.role,
  initials = excluded.initials,
  active = true;

insert into public.products
  (id, name_fr, name_ar, name_en, category, unit, unit_price_cents,
   image_position, image_url, purchase_count, active)
values
  (1, 'Lait entier', 'حليب كامل', 'Whole milk', 'food', 'L', 400, '0% 0%', '/products/milk-jouda.png', 18, true),
  (2, 'Pain rond', 'خبز دائري', 'Round bread', 'food', 'pièce', 200, '100% 0%', null, 24, true),
  (3, 'Huile d’olive', 'زيت الزيتون', 'Olive oil', 'food', 'L', 7500, '0% 0%', 'https://storage.googleapis.com/crftobringo-sharing-ma-prelive/ftp/CRF/images/571202-1-2.jpg', 8, true),
  (4, 'Farine fine', 'دقيق ناعم', 'Fine flour', 'food', 'kg', 800, '100% 100%', null, 13, true),
  (5, 'Sucre', 'سكر', 'Sugar', 'food', 'kg', 900, '0% 0%', 'https://media.carrefour.fr/medias/5127cba8d810345e86422a69e8d91a60/p_1500x1500/3560071410964-photosite-20211005-181348-0.jpg', 9, true),
  (6, 'Œufs', 'بيض', 'Eggs', 'food', 'pièce', 140, '0% 0%', 'https://media.carrefour.fr/medias/9af29a281e983cfe972ae7035de9bcd2/p_1500x1500/3348680000123-photosite-20160831-084739-0.jpg', 16, true),
  (7, 'Thé vert', 'شاي أخضر', 'Green tea', 'food', 'kg', 2000, '0% 0%', '/products/tea-assam-401.png', 6, true),
  (8, 'Lessive', 'مسحوق الغسيل', 'Laundry detergent', 'cleaning', 'kg', 3200, '0% 0%', 'https://storage.googleapis.com/crftobringo-sharing-ma-prelive/ftp/CRF/images/704718-1-2.jpg', 7, true),
  (9, 'Savon', 'صابون', 'Soap', 'hygiene', 'pièce', 650, '0% 0%', 'https://storage.googleapis.com/crftobringo-sharing-ma-prelive/ftp/CRF/images/747002-1-3.jpg', 10, true),
  (10, 'Dentifrice', 'معجون الأسنان', 'Toothpaste', 'hygiene', 'pièce', 1800, '0% 0%', 'https://storage.googleapis.com/crftobringo-sharing-ma-prelive/ftp/CRF/images/163607-1-2.jpg', 5, true),
  (11, 'Cahier', 'دفتر', 'Notebook', 'school', 'pièce', 1200, '0% 0%', 'https://media.carrefour.fr/medias/02251d8f86ee43908b21141159cf43e5/p_1500x1500/3616958825946_0.jpg', 3, true),
  (12, 'Papier cuisine', 'ورق المطبخ', 'Kitchen paper', 'household', 'pièce', 1500, '0% 0%', 'https://storage.googleapis.com/crftobringo-sharing-ma-prelive/ftp/CRF/images/530609-1-4.jpg', 4, true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.family_users', 'id'), greatest((select max(id) from public.family_users), 1), true);
select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1), true);

insert into public.app_meta (key, value)
values ('house_catalog_image_version', '3')
on conflict (key) do update set value = excluded.value;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
